# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: npm install, build, and test
      run: |
        npm install doctest
        npm install standard --save-dev
        npx doctest **/*.js || true  # TODO: Add all doctests
        npx standard
        npm ci
        npm run build --if-present
        
        npm test
        
    - name: Jest Test
      uses: raulanatol/jest-coverage-comment-action@main
      with:
        github-token: ${{ secrets.JAVASCRIPTTOKEN }}
        jest-command: 'npm run jest-ci'
        
      env:
        CI: true
        
